Adds email style
italia/docs-italia-convertitore-web pull request #29
Opened 2018-08-07 10:41 UTC by paoloromolini

![2018-08-07-124045_1476x654_scrot](https://user-images.githubusercontent.com/12033921/43771309-25924738-9a3f-11e8-8946-daf4546b0062.png)
Adds email template and css

2018-08-07 11:17 UTC, yakky reviewed
maybe we could use something like premailer to keep css and image in external files and compile into the email message only when the message is sent?

2018-08-07 11:32 UTC, paoloromolini commented
Sounds good, I've never done it though. Are you referring to something like that https://github.com/alexhayes/django-premailer ?

2018-08-07 13:49 UTC, yakky commented
Or https://github.com/peterbe/premailer (which we already use, you can ping @protoroto which has implemented it recently)

2018-08-14 07:49 UTC, yakky commented on docs_italia_convertitore_web/views.py
> +        process_file(email, saved, unique_key, options_json=options_json)
why removing this?

2018-08-14 07:52 UTC, yakky requested changes

2018-08-14 07:52 UTC, yakky commented on requirements_test.txt
> +premailer
We only need dependency in the main requirements file

2018-08-14 07:52 UTC, yakky commented on requirements_dev.txt
> +premailer
We only need dependency in the main requirements file

2018-08-14 09:11 UTC, yakky approved these changes

2018-08-14 14:08 UTC, francescozaia approved these changes

2018-08-14 14:20 UTC, merged